
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Areej kahlid
 */
public class frame2 extends javax.swing.JFrame {

    /**
     * Creates new form frame2
     */
    static int a=1;
    public frame2() {
        initComponents();
        order.setText(" "+a);
        a++;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton7 = new javax.swing.JButton();
        total = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        order = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(102, 102, 102));
        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 2));
        jTable1.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(255, 204, 51));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "S#", " Name", "Price", "Quantity", "Total"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTable1KeyPressed(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 540, 90));

        jButton7.setBackground(new java.awt.Color(51, 51, 51));
        jButton7.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 204, 51));
        jButton7.setText("DONE");
        jButton7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 350, 80, -1));

        total.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        total.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        total.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalActionPerformed(evt);
            }
        });
        jPanel1.add(total, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 220, 150, 30));

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 204, 0));
        jLabel2.setText("TOTAL BILL:");
        jLabel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 220, 140, -1));

        jLabel20.setBackground(new java.awt.Color(102, 102, 102));
        jLabel20.setFont(new java.awt.Font("Algerian", 3, 24)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 204, 51));
        jLabel20.setText("ORDER#");
        jLabel20.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 40, -1, -1));

        order.setFont(new java.awt.Font("Algerian", 3, 18)); // NOI18N
        order.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 51), 3));
        order.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderActionPerformed(evt);
            }
        });
        jPanel1.add(order, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 170, 30));

        jLabel21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/doll.png"))); // NOI18N
        jLabel21.setText("jLabel21");
        jPanel1.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 330, 220, -1));

        jPanel2.setBackground(new java.awt.Color(153, 0, 51));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setBackground(new java.awt.Color(204, 255, 255));
        jButton1.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(153, 0, 51));
        jButton1.setText("TASBEEH");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 80, 40));

        jButton2.setBackground(new java.awt.Color(204, 255, 255));
        jButton2.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(153, 0, 0));
        jButton2.setText("CAPS");
        jButton2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 140, 70, 40));

        jButton3.setBackground(new java.awt.Color(204, 255, 255));
        jButton3.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(153, 0, 51));
        jButton3.setText("ISLAMIC BOOK");
        jButton3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 51, 51), 2));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 110, 40));

        jButton4.setBackground(new java.awt.Color(204, 255, 255));
        jButton4.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton4.setForeground(new java.awt.Color(153, 0, 51));
        jButton4.setText("JAINAMAZ");
        jButton4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 190, 80, 40));

        jButton5.setBackground(new java.awt.Color(204, 255, 255));
        jButton5.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(153, 0, 51));
        jButton5.setText("ABAYA");
        jButton5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 190, 70, 40));

        jButton6.setBackground(new java.awt.Color(204, 255, 255));
        jButton6.setFont(new java.awt.Font("Arial", 3, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(153, 0, 51));
        jButton6.setText("STOLERS");
        jButton6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 2));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 100, 40));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, -1, -1));

        jPanel4.setBackground(new java.awt.Color(0, 51, 51));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 2));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 180, 160));

        jLabel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 2));
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 10, 180, 160));

        jLabel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 2));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 10, 180, 160));

        jLabel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 2));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 180, 160));

        jLabel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 2));
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 220, 180, 160));

        jLabel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 0, 51), 2));
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        jPanel4.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 220, 180, 160));

        jTextField2.setBackground(new java.awt.Color(153, 153, 153));
        jTextField2.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 204, 51));
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 80, 30));

        jTextField3.setBackground(new java.awt.Color(153, 153, 153));
        jTextField3.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jTextField3.setForeground(new java.awt.Color(255, 204, 51));
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jPanel4.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 180, 80, 30));

        jTextField4.setBackground(new java.awt.Color(153, 153, 153));
        jTextField4.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jTextField4.setForeground(new java.awt.Color(255, 204, 51));
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jPanel4.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 180, 80, 30));

        jTextField5.setBackground(new java.awt.Color(153, 153, 153));
        jTextField5.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jTextField5.setForeground(new java.awt.Color(255, 204, 51));
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel4.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 80, 30));

        jTextField6.setBackground(new java.awt.Color(153, 153, 153));
        jTextField6.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jTextField6.setForeground(new java.awt.Color(255, 204, 51));
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 0, 0), 2));
        jPanel4.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 80, 30));

        jTextField7.setBackground(new java.awt.Color(153, 153, 153));
        jTextField7.setFont(new java.awt.Font("Algerian", 3, 14)); // NOI18N
        jTextField7.setForeground(new java.awt.Color(255, 204, 51));
        jPanel4.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 390, 80, 30));

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 850, 920));

        jLabel1.setBackground(new java.awt.Color(153, 153, 153));
        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setText("ITEMS");
        jLabel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 2));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 90, 80, 40));

        jPanel6.setBackground(new java.awt.Color(0, 51, 51));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 204, 0), 3));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front icon1.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel6.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 30, 40, 50));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front icon2.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel6.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 40, 38, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon5.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel6.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 40, 36, 40));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon14.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 30, 39, 60));

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon4.png"))); // NOI18N
        jLabel13.setText("jLabel13");
        jPanel6.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 32, 40));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon3.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel6.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 30, 54, 53));

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon11.png"))); // NOI18N
        jLabel15.setText("jLabel15");
        jPanel6.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 40, 40, 50));

        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon12.png"))); // NOI18N
        jLabel16.setText("jLabel16");
        jPanel6.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 40, 40, -1));

        jLabel17.setBackground(new java.awt.Color(255, 204, 0));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon13.png"))); // NOI18N
        jLabel17.setText("jLabel17");
        jPanel6.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 40, 70));

        jLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon10.png"))); // NOI18N
        jLabel18.setText("jLabel18");
        jPanel6.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 46, 60));

        jLabel19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/front icon1.png"))); // NOI18N
        jLabel19.setText("jLabel10");
        jPanel6.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 40, 50));

        jPanel2.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 760, 90));

        jLabel22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/chooza.png"))); // NOI18N
        jLabel22.setText("jLabel22");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 100, 110));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 761, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1409, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1161, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
int tablerow=0;
int price;
int c=0;
int totalp=0;
    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        frame3 b=new frame3();
        b.setVisible(true);
        String t=total.getText();
        b.totalbill.setText(t);
       //for oder no
        String f=order.getText();
        b.jTextField1.setText(""+f);
        
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        c=1;
        if(jButton1.isEnabled()){
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tasbih4.jpg"))); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tasbih 5.jpg"))); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tasbih 9.png"))); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tasbih6.png"))); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/tasbih8.jpg"))); // NOI18N
         jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource(""))); // NOI18N
        
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jTextField2.setText("500");
        jTextField3.setText("1000");
        jTextField4.setText("400");
        jTextField5.setText("650");
        jTextField6.setText("800");
        jTextField7.setText("");
       }
        else
        {
            jLabel3.setIcon(null);
            jLabel4.setIcon(null);
            jLabel5.setIcon(null);
            jLabel6.setIcon(null);
            jLabel7.setIcon(null);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        c=2;
        if(jButton2.isEnabled()){
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/muslim-caps-250x250.jpg"))); // NOI18N
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cap.jpg"))); // NOI18N
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cap4.jpg"))); // NOI18N
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/capp.png"))); // NOI18N
            jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cap3.jpg"))); // NOI18N
            jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cap6.jpg"))); // NOI18N
          jLabel3.setVisible(true);
          jLabel4.setVisible(true);
          jLabel5.setVisible(true);
          jLabel6.setVisible(true);
          jLabel7.setVisible(true);
          jLabel8.setVisible(true);
          jTextField2.setText("400");
        jTextField3.setText("600");
        jTextField4.setText("800");
        jTextField5.setText("850");
        jTextField6.setText("700");
        jTextField7.setText("1000");
          
        }
        else
        {
            jLabel3.setIcon(null);
            jLabel4.setIcon(null);
            jLabel5.setIcon(null);
            jLabel6.setIcon(null);
            jLabel7.setIcon(null);
            jLabel8.setIcon(null);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        c=3;
        if(jButton3.isEnabled()){
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book6.jpg"))); // NOI18N
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book2.JPG"))); // NOI18N
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book5.jpg"))); // NOI18N
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/book7.jpg"))); // NOI18N
             jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(" "))); // NOI18N
              jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource(" "))); // NOI18N
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jTextField2.setText("1000");
        jTextField3.setText("1500");
        jTextField4.setText("1700");
        jTextField5.setText("2000");
        jTextField6.setText("");
        jTextField7.setText("");
        }
        else
        {
            jLabel3.setIcon(null);
            jLabel4.setIcon(null);
            jLabel5.setIcon(null);
            jLabel6.setIcon(null);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        c=4;
        if(jButton4.isEnabled()){
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jai namaz2.jpg"))); // NOI18N
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jai namaz3.png"))); // NOI18N
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/jai namaz5.jpg"))); // NOI18N
             jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource(" "))); // NOI18N
              jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource(" "))); // NOI18N
               jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource(" "))); // NOI18N
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jTextField2.setText("700");
        jTextField3.setText("1000");
        jTextField4.setText("1200");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        }
        else
        {
            jLabel3.setIcon(null);
            jLabel4.setIcon(null);
            jLabel5.setIcon(null);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        c=5;
        if(jButton5.isEnabled()){
        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abaya 1.JPG"))); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abaya2.jpg"))); // NOI18N
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abaya4.jpg"))); // NOI18N
        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abaya5.jpg"))); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/abaya6.jpg"))); // NOI18N
         jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource(" "))); // NOI18N
        jLabel3.setVisible(true);
        jLabel4.setVisible(true);
        jLabel5.setVisible(true);
        jLabel6.setVisible(true);
        jLabel7.setVisible(true);
        jTextField2.setText("1600");
        jTextField3.setText("1500");
        jTextField4.setText("2000");
        jTextField5.setText("2500");
        jTextField6.setText("1800");
        jTextField7.setText("");
        
        }
        else{
            jLabel3.setIcon(null);
            jLabel4.setIcon(null);
            jLabel5.setIcon(null);
            jLabel6.setIcon(null);
            jLabel7.setIcon(null);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        c=6;
        if(jButton6.isEnabled()){
            jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stole1.jpg"))); // NOI18N
            jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stole3.jpg"))); // NOI18N
            jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stole4.jpg"))); // NOI18N
            jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stole9.jpg"))); // NOI18N
            jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stolaaaarrr.jpg"))); // NOI18N
            jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/stolerrrr.jpg"))); // NOI18N
            jLabel3.setVisible(true);
            jLabel4.setVisible(true);
            jLabel5.setVisible(true);
            jLabel6.setVisible(true);
            jLabel7.setVisible(true);
            jLabel8.setVisible(true);
            jTextField2.setText("600");
        jTextField3.setText("1000");
        jTextField4.setText("650");
        jTextField5.setText("850");
        jTextField6.setText("700");
        jTextField7.setText("450");
            
        }
        else
        {
            jLabel3.setIcon(null);
            jLabel4.setIcon(null);
            jLabel5.setIcon(null);
            jLabel6.setIcon(null);
            jLabel7.setIcon(null);
            jLabel8.setIcon(null);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jTable1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTable1KeyPressed

        int index=jTable1.getSelectedRow();
        TableModel mode7=jTable1.getModel();
        int value1=Integer.parseInt(mode7.getValueAt(index,2).toString());
        int value2=Integer.parseInt(mode7.getValueAt(index,3).toString());
        int value3=value1*value2;
        mode7.setValueAt(value3, index ,4);
        jTable1.setModel(mode7);
        totalp= totalp+value3;
        total.setText(totalp+"");
        
    }//GEN-LAST:event_jTable1KeyPressed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
     DefaultTableModel mode1=(DefaultTableModel)jTable1.getModel();
     mode1.addRow(new Object[]{tablerow+1});
     switch(c) {
         case 1:
             price=Integer.parseInt(jTextField2.getText());
             mode1.setValueAt(mode1.getRowCount(), tablerow, 0);
             mode1.setValueAt("Tasbeeh",tablerow, 1);
             mode1.setValueAt(price, tablerow, 2);
             jTable1.setModel(mode1);
             tablerow++;
             break;
         case 2:
             price=Integer.parseInt(jTextField2.getText());
              mode1.setValueAt(mode1.getRowCount(), tablerow, 0);
           mode1.setValueAt("Cap", tablerow, 1);
             mode1.setValueAt(price, tablerow, 2);
             jTable1.setModel(mode1);
             tablerow++;
             break;
         case 3:
             price=Integer.parseInt(jTextField2.getText());
              mode1.setValueAt(mode1.getRowCount(), tablerow, 0);
             mode1.setValueAt( "Islamic book", tablerow, 1);
             mode1.setValueAt(price, tablerow, 2);
             jTable1.setModel(mode1);
             tablerow++;
             break;
         case 4:
             price=Integer.parseInt(jTextField2.getText());
              mode1.setValueAt(mode1.getRowCount(), tablerow, 0);
             mode1.setValueAt("Jainamaz", tablerow, 1);
             mode1.setValueAt(price, tablerow, 2);
             jTable1.setModel(mode1);
             tablerow++;
             break;
         case 5:
             price=Integer.parseInt(jTextField2.getText());
              mode1.setValueAt(mode1.getRowCount(), tablerow, 0);
             mode1.setValueAt("Abaya", tablerow, 1);
             mode1.setValueAt(price, tablerow, 2);
             jTable1.setModel(mode1);
             tablerow++;
             break;
         case 6:
             price=Integer.parseInt(jTextField2.getText());
              mode1.setValueAt(mode1.getRowCount(), tablerow, 0);
             mode1.setValueAt("Stoler", tablerow, 1);
             mode1.setValueAt(price, tablerow, 2);
             jTable1.setModel(mode1);
             tablerow++;
             break;
         default:
             break;

    }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        DefaultTableModel mode2=(DefaultTableModel)jTable1.getModel();
        mode2.addRow(new Object[]{tablerow+1});
        switch (c){
            case 1:
                price=Integer.parseInt(jTextField3.getText());
                mode2.setValueAt(mode2.getRowCount(), tablerow, 0);
                mode2.setValueAt("Tasbeeh", tablerow, 1);
                mode2.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode2);
                tablerow++;
                break;
            case 2:
                price=Integer.parseInt(jTextField3.getText());
                 mode2.setValueAt(mode2.getRowCount(), tablerow, 0);
                mode2.setValueAt("Cap", tablerow, 1);
                mode2.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode2);
                tablerow++;
                break;
            case 3:
                price=Integer.parseInt(jTextField3.getText());
                 mode2.setValueAt(mode2.getRowCount(), tablerow, 0);
                mode2.setValueAt("Islamic book", tablerow, 1);
                mode2.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode2);
                tablerow++;
                break;
            case 4:
                price=Integer.parseInt(jTextField3.getText());
                 mode2.setValueAt(mode2.getRowCount(), tablerow, 0);
                mode2.setValueAt("Jainamaz", tablerow, 1);
                mode2.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode2);
                tablerow++;
                break;
            case 5:
                price=Integer.parseInt(jTextField3.getText());
                 mode2.setValueAt(mode2.getRowCount(), tablerow, 0);
                mode2.setValueAt("Abaya", tablerow, 1);
                mode2.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode2);
                tablerow++;
                break;
            case 6:
                price=Integer.parseInt(jTextField3.getText());
                 mode2.setValueAt(mode2.getRowCount(), tablerow, 0);
                mode2.setValueAt("Stoler", tablerow, 1);
                mode2.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode2);
                tablerow++;
                break;
            default:
                break;
        }
        
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        DefaultTableModel mode3=(DefaultTableModel)jTable1.getModel();
        mode3.addRow(new Object[]{tablerow+1});
        switch (c){
            case 1:
                price=Integer.parseInt(jTextField4.getText());
                mode3.setValueAt(mode3.getRowCount(), tablerow, 0);
                mode3.setValueAt("Tasbeeh", tablerow, 1);
                mode3.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode3);
                tablerow++;
                break;
            case 2:
                price=Integer.parseInt(jTextField4.getText());
                mode3.setValueAt(mode3.getRowCount(), tablerow, 0);
                mode3.setValueAt("Cap", tablerow, 1);
                mode3.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode3);
                tablerow++;
                break;
            case 3:
                price=Integer.parseInt(jTextField4.getText());
                mode3.setValueAt(mode3.getRowCount(), tablerow, 0);
                mode3.setValueAt("Islamic book", tablerow, 1);
                mode3.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode3);
                tablerow++;
                break;
            case 4:
                price=Integer.parseInt(jTextField4.getText());
                mode3.setValueAt(mode3.getRowCount(), tablerow, 0);
                mode3.setValueAt("jainamaz", tablerow, 1);
                mode3.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode3);
                tablerow++;
                break;
            case 5:
                price=Integer.parseInt(jTextField4.getText());
                mode3.setValueAt(mode3.getRowCount(), tablerow, 0);
                mode3.setValueAt("Abaya", tablerow, 1);
                mode3.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode3);
                tablerow++;
                break;
            case 6:
                price=Integer.parseInt(jTextField4.getText());
                mode3.setValueAt(mode3.getRowCount(), tablerow, 0);
                mode3.setValueAt("Stoler", tablerow, 1);
                mode3.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode3);
                tablerow++;
                break;
            default:
                break;
        }
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        DefaultTableModel mode4=(DefaultTableModel)jTable1.getModel();
        mode4.addRow(new Object[]{tablerow+1});
        switch(c){
            case 1:
                price=Integer.parseInt(jTextField5.getText());
                mode4.setValueAt(mode4.getRowCount(), tablerow, 0);
                mode4.setValueAt("Tasbeeh", tablerow, 1);
                mode4.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode4);
                tablerow++;
                break;
            case 2:
                price=Integer.parseInt(jTextField5.getText());
                mode4.setValueAt(mode4.getRowCount(), tablerow, 0);
                mode4.setValueAt("Cap", tablerow, 1);
                mode4.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode4);
                tablerow++;
            case 3:
                price=Integer.parseInt(jTextField5.getText());
                mode4.setValueAt(mode4.getRowCount(), tablerow, 0);
                mode4.setValueAt("islamic book", tablerow, 1);
                mode4.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode4);
                tablerow++;
            case 4:
                price=Integer.parseInt(jTextField5.getText());
                mode4.setValueAt(mode4.getRowCount(), tablerow, 0);
                mode4.setValueAt("Jainamaz", tablerow, 1);
                mode4.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode4);
                tablerow++;
            case 5:
                price=Integer.parseInt(jTextField5.getText());
                mode4.setValueAt(mode4.getRowCount(), tablerow, 0);
                mode4.setValueAt("Abaya", tablerow, 1);
                mode4.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode4);
                tablerow++;
            case 6:
                price=Integer.parseInt(jTextField5.getText());
                mode4.setValueAt(mode4.getRowCount(), tablerow, 0);
                mode4.setValueAt("Stoler", tablerow, 1);
                mode4.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode4);
                tablerow++;
            default:
                break;
                
        }
        
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        DefaultTableModel mode5=(DefaultTableModel)jTable1.getModel();
        mode5.addRow(new Object[]{tablerow+1});
        switch(c){
            case 1:
                price=Integer.parseInt(jTextField6.getText());
                mode5.setValueAt(mode5.getRowCount(), tablerow, 0);
                mode5.setValueAt("Tasbeeh", tablerow, 1);
                mode5.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode5);
                tablerow++;
                break;
            case 2:
                price=Integer.parseInt(jTextField6.getText());
                mode5.setValueAt(mode5.getRowCount(), tablerow, 0);
                mode5.setValueAt("Cap", tablerow, 1);
                mode5.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode5);
                tablerow++;
            case 3:
                price=Integer.parseInt(jTextField6.getText());
                mode5.setValueAt(mode5.getRowCount(), tablerow, 0);
                mode5.setValueAt("islamic book", tablerow, 1);
                mode5.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode5);
                tablerow++;
            case 4:
                price=Integer.parseInt(jTextField6.getText());
                mode5.setValueAt(mode5.getRowCount(), tablerow, 0);
                mode5.setValueAt("Jainamaz", tablerow, 1);
                mode5.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode5);
                tablerow++;
            case 5:
                price=Integer.parseInt(jTextField6.getText());
                mode5.setValueAt(mode5.getRowCount(), tablerow, 0);
                mode5.setValueAt("Abaya", tablerow, 1);
                mode5.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode5);
                tablerow++;
            case 6:
                price=Integer.parseInt(jTextField6.getText());
                mode5.setValueAt(mode5.getRowCount(), tablerow, 0);
                mode5.setValueAt("Stoler", tablerow, 1);
                mode5.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode5);
                tablerow++;
            default:
                break;
        }
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        DefaultTableModel mode6=(DefaultTableModel)jTable1.getModel();
        mode6.addRow(new Object[]{tablerow+1});
        switch(c){
            case 1:
                price=Integer.parseInt(jTextField7.getText());
                mode6.setValueAt(mode6.getRowCount(), tablerow, 0);
                mode6.setValueAt("Tasbeeh", tablerow, 1);
                mode6.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode6);
                tablerow++;
                break;
            case 2:
                price=Integer.parseInt(jTextField7.getText());
                mode6.setValueAt(mode6.getRowCount(), tablerow, 0);
                mode6.setValueAt("Cap", tablerow, 1);
                mode6.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode6);
                tablerow++;
            case 3:
                price=Integer.parseInt(jTextField7.getText());
                mode6.setValueAt(mode6.getRowCount(), tablerow, 0);
                mode6.setValueAt("islamic book", tablerow, 1);
                mode6.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode6);
                tablerow++;
            case 4:
                price=Integer.parseInt(jTextField7.getText());
                mode6.setValueAt(mode6.getRowCount(), tablerow, 0);
                mode6.setValueAt("Jainamaz", tablerow, 1);
                mode6.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode6);
                tablerow++;
            case 5:
                price=Integer.parseInt(jTextField7.getText());
                mode6.setValueAt(mode6.getRowCount(), tablerow, 0);
                mode6.setValueAt("Abaya", tablerow, 1);
                mode6.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode6);
                tablerow++;
            case 6:
                price=Integer.parseInt(jTextField7.getText());
                mode6.setValueAt(mode6.getRowCount(), tablerow, 0);
                mode6.setValueAt("Stoler", tablerow, 1);
                mode6.setValueAt(price, tablerow, 2);
                jTable1.setModel(mode6);
                tablerow++;
            default:
                break;
        }
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void orderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_orderActionPerformed

    private void totalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField order;
    private javax.swing.JTextField total;
    // End of variables declaration//GEN-END:variables
}
